namespace Hungath
{
	public enum TileType
	{
		Land,
		Berry,
		Goat,
		Predator,
		Fish,
		Herd,
		SetPlague,
		SetOasis,
		SetFertilityRites,
		SetHuntingNet,
		SetWanderingNomads,
		SetHuntingMap,
		SetAncientFarm,
		SetPredatorDen,
		SetRot,
		SetRockSlide,
		SetStampede,
		BonusSilos,
		BonusImprovedArrows,
		BonusImprovedBaskets,
		BonusCelestialLight,
		BonusHandOfMidas,
		BonusExperienced,
		BonusHunterOfHunters,
		BonusTracking,
		BonusReapingTools,
		BonusForagingParty,
		BonusLiveOffTheLand,
		BonusHardBellies,
		BonusEvasionTactics,
		BonusTwinning,
		BonusRomanticAllure
	}
}